services:
  betatrax:
    build: .
    container_name: betatrax
    environment:
      - POSTGRES_NAME=betatrax
      - POSTGRES_USER=betatrax
      - POSTGRES_PASSWORD=betatrax
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DJANGO_PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./data/BetaTrax:/app/BetaTrax/migrations
      - ./data/Tenants:/app/Tenants/migrations
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=betatrax
      - POSTGRES_PASSWORD=betatrax
      - POSTGRES_DB=betatrax
      - POSTGRES_PORT=5432
    volumes:
      - ./data/postgres:/var/lib/postgresql