# Generated by Django 6.0.3 on 2026-03-26 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('DEVELOPER', 'Developer')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='BetaTrax.product')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('ASSIGNED', 'Assigned'), ('FIXED', 'Fixed'), ('CANNOT_REPRODUCE', 'Cannot Reproduce'), ('REOPENED', 'Reopened'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.IntegerField(choices=[(3, 'Critical'), (2, 'Major'), (1, 'Minor'), (0, 'Low')], null=True)),
                ('priority', models.IntegerField(choices=[(3, 'Critical'), (2, 'High'), (1, 'Medium'), (0, 'Low')], null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('reproduce_steps', models.TextField()),
                ('version', models.CharField(max_length=20, null=True)),
                ('tester_ID', models.CharField(max_length=20)),
                ('tester_email', models.EmailField(max_length=254, null=True)),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BetaTrax.report')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BetaTrax.product')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BetaTrax.report')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
