# Generated by Django 6.0.3 on 2026-03-21 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('DEVELOPER', 'Developer')], max_length=20, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BetaTrax.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('ASSIGNED', 'Assigned'), ('FIXED', 'Fixed'), ('CANNOT_REPRODUCE', 'Cannot Reproduce'), ('REOPENED', 'Reopened'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor'), ('LOW', 'Low')], max_length=20, null=True)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tester_email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BetaTrax.employee')),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BetaTrax.report')),
            ],
        ),
    ]
