# Generated by Django 6.0.3 on 2026-03-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetaTrax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='tester_ID',
            new_name='tester_id',
        ),
    ]
