# Generated by Django 6.0.3 on 2026-03-26 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetaTrax', '0002_rename_tester_id_report_tester_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('OPENED', 'Opened'), ('REJECTED', 'Rejected'), ('DUPLICATED', 'Duplicated'), ('ASSIGNED', 'Assigned'), ('FIXED', 'Fixed'), ('COULDNT_REPRODUCE', 'Couldnt Reproduce'), ('REOPENED', 'Reopened'), ('RESOLVED', 'Resolved')], max_length=20),
        ),
    ]
